#!/bin/bash

if [[ $# -ne 1 ]]; then
    echo "Use the contest name as argument."
    exit 1
fi

rm a.out
rm CDF_template.cpp
rm create_test.py
rm help_functions.cpp
rm test.sh
rm end
cd ../
mv temp $1
./init
